name: GatewaySolution

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: Mango.GatewaySolution
      run: dotnet restore
    - name: Build
      working-directory: Mango.GatewaySolution
      run: dotnet build --no-restore
